package it.polimi.ingsw.View.User;

/**
 * Enum class containing all the actions that the server can send to the client.
 */
public enum UIActions {
    CHOOSE_NAME, CHOOSE_NUMBER_OF_PLAYERS, INITIAL_CHOOSE_LEADER_CARDS, INITIAL_LOBBY, INITIAL_CHOOSE_RESOURCES, INITIAL_CHOOSE_RESOURCES_ERROR,
    RECONNECTION, PLAY_TURN, FINAL_POINTS, DISPLAY_ACTION, DISPLAY_ERROR, SINGLEPLAYER_TURN, SINGLEPLAYER_END_WON, SINGLEPLAYER_END_LOST,
    RESTART_OR_CONTINUE,

    WAITING
}